### ISSUE TITLE
Cannot login after creating an account.

### ISSUE THREAD

**Issue by miikkuu** [ImranMir32/I-Blogify#1]
i tried your app locally but after clicking in create account and creeating the account i am redirected to login page but it always says invalid credentials.I have tried creating multiple accounts.

the account creadentials gets logged on to console meaning the accounts are getting created but we cannot login it alwsys says wrong credntials.

please see and help me. I am student learning node

**Comment by ImranMir32** [comment]
Check your database carefully and also the login route maybe when you are sending login credentials there are some issues
